
CREATE TABLE chunk_data (
    id BIGINT NOT NULL PRIMARY KEY,
    pageNumber INTEGER NOT NULL,
    bookId INTEGER NOT NULL,
    data TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);