import {
  sqliteTable,
  text,
  integer,
  real,
  primaryKey,
  index,
  uniqueIndex,
  foreignKey,
  type AnySQLiteColumn,
} from "drizzle-orm/sqlite-core";

export const user = sqliteTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email"),
  emailVerified: integer("email_verified", { mode: "boolean" }).notNull(),
  image: text("image"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  // Added by @better-auth/stripe plugin. Populated by createCustomerOnSignUp.
  stripeCustomerId: text("stripe_customer_id"),
});

export const appleUsers = sqliteTable("apple_users", {
  id: text("id").primaryKey(), // UUID generated by your app

  appleUserId: text("apple_user_id").notNull().unique(),
  userId: text("user_id").references(() => user.id, { onDelete: "cascade" }),

  email: text("email"),

  emailVerified: integer("email_verified", {
    mode: "boolean",
  }).notNull(),

  privateEmail: integer("private_email", {
    mode: "boolean",
  }).notNull(),

  siwaRefreshTokenCiphertext: text("siwa_refresh_token_ciphertext"),
  siwaRefreshTokenNonce: text("siwa_refresh_token_nonce"),

  createdAt: integer("created_at", {
    mode: "timestamp_ms",
  })
    .$defaultFn(() => new Date())
    .notNull(),

  updatedAt: integer("updated_at", {
    mode: "timestamp_ms",
  })
    .$defaultFn(() => new Date())
    .$onUpdateFn(() => new Date())
    .notNull(),
});

export const account = sqliteTable("account", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: integer("access_token_expires_at", { mode: "timestamp" }),
  refreshTokenExpiresAt: integer("refresh_token_expires_at", { mode: "timestamp" }),
  scope: text("scope"),
  password: text("password"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});

export const userApiUsage = sqliteTable("user_api_usage", {
  userId: text("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  voiceChatRequests: integer("voice_chat_requests").notNull().default(0),
  ttsRequests: integer("tts_requests").notNull().default(0),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

// ─── Books table ───────────────────────────────────────────────────────────────
// Matches mobile SQLite schema columns (snake_case) plus sync-specific columns.
// filePath and coverPath exist in the schema definition for mobile use but are
// NEVER written to D1 on the server side (they are local-only paths).
export const books = sqliteTable("books", {
  id: text("id").primaryKey(), // UUID, client-generated
  userId: text("user_id").references(() => user.id, { onDelete: "cascade" }), // null on mobile (single-user), set by server during push
  title: text("title").notNull(),
  author: text("author").notNull().default("Unknown"),
  coverPath: text("cover_path"), // local path -- mobile-only, never synced to D1
  filePath: text("file_path").notNull(), // local path -- mobile-only, never synced to D1
  format: text("format").notNull().default("epub"),
  currentCfi: text("current_cfi"), // EPUB reading position
  currentPage: integer("current_page"), // PDF reading position
  // #41 — Persisted 0..1 progress float used to render the library
  // "Reading Now" pill subline AFTER the reader has been closed. EPUB
  // sources this from epubjs's onRelocated progress arg; PDF/DJVU and
  // MOBI/AZW3 derive it at save time from their own page/chapter
  // counts. Stored as SQLite REAL (drizzle `real()`); mobile-only —
  // never pushed to D1 (the server can reconstruct progress from
  // page/cfi if needed and we don't want to widen the wire payload).
  lastProgressPercent: real("last_progress_percent"), // 0..1 float or null
  fileHash: text("file_hash"), // SHA-256 for R2 dedup
  fileR2Key: text("file_r2_key"), // R2 object key for book file
  coverR2Key: text("cover_r2_key"), // R2 object key for cover image
  fileSize: integer("file_size").default(0), // bytes — populated by client on push; used for per-user storage cap
  // DAT-003: mobile-only recovery flag. Set to true when an R2 download
  // succeeded but the atomic `tmpFile.move()` into the final destination
  // failed. The temp file is kept on disk so a retry doesn't have to
  // re-fetch bytes; UI surfaces these via the download-error-store.
  // Never synced to D1.
  fileNeedsRedownload: integer("file_needs_redownload", {
    mode: "boolean",
  }).default(false),
  createdAt: integer("created_at").notNull(), // Unix timestamp ms
  updatedAt: integer("updated_at").notNull(), // Unix timestamp ms
  syncVersion: integer("sync_version").default(0), // server-assigned monotonic counter
  isDirty: integer("is_dirty", { mode: "boolean" }).default(true), // needs push
  isDeleted: integer("is_deleted", { mode: "boolean" }).default(false), // soft delete
  // Path E text-extraction status. Populated by the import-time runner.
  extractionStatus: text("extraction_status"), // 'pending' | 'extracting' | 'extracted' | 'error'
  extractedPages: integer("extracted_pages").default(0),
  totalPages: integer("total_pages"),
  extractionError: text("extraction_error"),
});

// ─── Chapter index sync ─────────────────────────────────────────────────────
// One parent row is the LWW envelope; child rows retain the normalized,
// ordered chapter summaries for a single content version.
export const chapterIndexes = sqliteTable(
  "chapter_indexes",
  {
    id: text("id").notNull(),
    userId: text("user_id").notNull().references(() => user.id, { onDelete: "cascade" }),
    bookId: text("book_id").notNull().references(() => books.id, { onDelete: "cascade" }),
    contentVersion: text("content_version").notNull(),
    status: text("status", { enum: ["building", "ready", "unavailable", "failed"] }).notNull(),
    modelIdentifier: text("model_identifier").notNull(),
    modelVersion: text("model_version").notNull(),
    completedCount: integer("completed_count").notNull().default(0),
    totalCount: integer("total_count").notNull().default(0),
    errorMessage: text("error_message"),
    createdAt: integer("created_at").notNull(),
    updatedAt: integer("updated_at").notNull(),
  },
  (t) => ({
    pk: primaryKey({ columns: [t.userId, t.bookId, t.contentVersion] }),
    byUserUpdated: index("chapter_indexes_user_updated_idx").on(t.userId, t.updatedAt),
    versionKey: uniqueIndex("chapter_indexes_version_key_uniq").on(t.userId, t.bookId, t.contentVersion),
  }),
);

export const chapterIndexChapters = sqliteTable(
  "chapter_index_chapters",
  {
    id: text("id").primaryKey(),
    userId: text("user_id").notNull().references(() => user.id, { onDelete: "cascade" }),
  bookId: text("book_id").notNull().references(() => books.id, { onDelete: "cascade" }),
    contentVersion: text("content_version").notNull(),
    chapterId: text("chapter_id").notNull(),
    sourcePosition: integer("source_position").notNull(),
    name: text("name").notNull(),
    summary: text("summary").notNull(),
    createdAt: integer("created_at").notNull(),
    updatedAt: integer("updated_at").notNull(),
  },
  (t) => ({
    uniqueChapter: uniqueIndex("chapter_index_chapters_version_chapter_uniq").on(
      t.userId, t.bookId, t.contentVersion, t.chapterId,
    ),
    byVersionOrder: index("chapter_index_chapters_version_order_idx").on(
      t.userId, t.bookId, t.contentVersion, t.sourcePosition,
    ),
    parent: foreignKey({
      columns: [t.userId, t.bookId, t.contentVersion],
      foreignColumns: [chapterIndexes.userId, chapterIndexes.bookId, chapterIndexes.contentVersion],
      name: "chapter_index_chapters_parent_fk",
    }).onDelete("cascade"),
  }),
);

// ─── Sync metadata table ───────────────────────────────────────────────────────
// Tracks sync state on the client. Single row with id='default'.
export const syncMeta = sqliteTable("sync_meta", {
  id: text("id").primaryKey(), // always 'default'
  lastSyncVersion: integer("last_sync_version").default(0),
  lastSyncAt: integer("last_sync_at"), // Unix timestamp ms
});

// ─── Highlights table ─────────────────────────────────────────────────────────
// Stores text highlights/annotations for books with sync support.
export const highlights = sqliteTable("highlights", {
  id: text("id").primaryKey(), // UUID, client-generated
  bookId: text("book_id").notNull().references(() => books.id, { onDelete: "cascade" }), // FK to books.id
  userId: text("user_id").references(() => user.id, { onDelete: "cascade" }), // null on mobile, set by server
  cfiRange: text("cfi_range").notNull(), // ePubCFI range string
  text: text("text").notNull(), // selected text content
  color: text("color").notNull().default("yellow"), // yellow, green, blue, pink
  note: text("note"), // optional annotation text
  chapter: text("chapter"), // chapter/section label for display
  createdAt: integer("created_at").notNull(), // Unix timestamp ms
  updatedAt: integer("updated_at").notNull(), // Unix timestamp ms
  syncVersion: integer("sync_version").default(0), // server-assigned monotonic counter
  isDirty: integer("is_dirty", { mode: "boolean" }).default(true), // needs push
  isDeleted: integer("is_deleted", { mode: "boolean" }).default(false), // soft delete
});

// ─── Conversations table ──────────────────────────────────────────────────────
// Stores conversation threads tied to books with sync support.
// Phase 16-01: userId tightened to NOT NULL + FK ON DELETE CASCADE so the
// chat-sync routes can scope queries to the caller via Better Auth session.
// (user_id, updated_at) index powers since-cursor scans for /api/sync/conversations.
export const conversations = sqliteTable(
  "conversations",
  {
    id: text("id").primaryKey(), // UUID, client-generated
    // Kept as a required book identifier for the sync contract, but not a
    // foreign key: legacy production data contains conversation rows whose
    // book was removed. User ownership is enforced by userId's cascade.
    bookId: text("book_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    title: text("title").notNull().default("New conversation"),
    createdAt: integer("created_at").notNull(), // Unix timestamp ms
    updatedAt: integer("updated_at").notNull(), // Unix timestamp ms
    syncVersion: integer("sync_version").default(0),
    isDirty: integer("is_dirty", { mode: "boolean" }).default(true),
    isDeleted: integer("is_deleted", { mode: "boolean" }).default(false),
  },
  (t) => ({
    byUserUpdated: index("conversations_user_updated_idx").on(
      t.userId,
      t.updatedAt,
    ),
  }),
);

// ─── Bookmarks table ─────────────────────────────────────────────────────────
// Stores EPUB (and future PDF) bookmarks with sync support. Mirrors the
// `BookmarkRow` shape exported by `@rishi/shared/formats/bookmark-cfi` —
// adding a typed Drizzle definition so both clients can share the same
// schema and `db.insert(bookmarks).values(...)` is type-checked.
export const bookmarks = sqliteTable("bookmarks", {
  id: text("id").primaryKey(), // UUID, client-generated
  bookId: text("book_id").notNull().references(() => books.id, { onDelete: "cascade" }), // FK to books.id
  userId: text("user_id").references(() => user.id, { onDelete: "cascade" }), // null on mobile, set by server
  location: text("location").notNull(), // EPUB CFI / PDF page locator
  label: text("label").notNull().default(""),
  snippet: text("snippet"), // optional surrounding-text excerpt (iOS Bookmark.snippet); nullable
  pageNumber: integer("page_number"), // optional page hint for PDF parity
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
  syncVersion: integer("sync_version").default(0),
  isDirty: integer("is_dirty", { mode: "boolean" }).default(true),
  isDeleted: integer("is_deleted", { mode: "boolean" }).default(false),
});

// ─── Messages table ──────────────────────────────────────────────────────────
// Stores individual messages within conversations. Append-only during sync.
// Phase 16-01: (conversation_id, updated_at) index powers join-then-since fetch
// for /api/sync/messages. Per-row ownership is enforced via the parent
// conversation's userId FK at query time (no per-message FK to user).
export const messages = sqliteTable(
  "messages",
  {
    id: text("id").primaryKey(), // UUID, client-generated
    conversationId: text("conversation_id").notNull().references(() => conversations.id, { onDelete: "cascade" }), // FK to conversations.id
    role: text("role").notNull(), // 'user' | 'assistant'
    content: text("content").notNull(),
    sourceChunks: text("source_chunks"), // JSON-serialized SourceChunk[]
    createdAt: integer("created_at").notNull(), // Unix timestamp ms
    updatedAt: integer("updated_at").notNull(), // Unix timestamp ms
    syncVersion: integer("sync_version").default(0),
    isDirty: integer("is_dirty", { mode: "boolean" }).default(true),
    isDeleted: integer("is_deleted", { mode: "boolean" }).default(false),
  },
  (t) => ({
    byConvUpdated: index("messages_conv_updated_idx").on(
      t.conversationId,
      t.updatedAt,
    ),
  }),
);

// ─── Book pages: extracted plain text per page ───────────────────────────────
// Populated once at import time by rishi-pdf-extractor. Coordinates everywhere
// in this group of tables are in PDF user-space (origin bottom-left, points).
export const bookPages = sqliteTable(
  "book_pages",
  {
  bookId: text("book_id").notNull().references(() => books.id, { onDelete: "cascade" }),
    pageNumber: integer("page_number").notNull(),
    text: text("text").notNull().default(""),
    widthPts: real("width_pts").notNull(),
    heightPts: real("height_pts").notNull(),
    indexedAt: integer("indexed_at").notNull(),
  },
  (table) => ({
    pk: primaryKey({ columns: [table.bookId, table.pageNumber] }),
  }),
);

// ─── Book words: per-word bounding boxes for hit-testing + highlights ────────
export const bookWords = sqliteTable(
  "book_words",
  {
  bookId: text("book_id").notNull().references(() => books.id, { onDelete: "cascade" }),
    pageNumber: integer("page_number").notNull(),
    idx: integer("idx").notNull(),
    text: text("text").notNull(),
    x: real("x").notNull(),
    y: real("y").notNull(),
    w: real("w").notNull(),
    h: real("h").notNull(),
  },
  (table) => ({
    pk: primaryKey({ columns: [table.bookId, table.pageNumber, table.idx] }),
  }),
);

// ─── Book paragraphs: TTS-ready paragraph chunks ─────────────────────────────
// Index strings mirror the existing pdfjs shape: `${pageNumber*10000 + i}`
// so the resolvePlayFromSelection consumer needs no adapter.
export const bookParagraphs = sqliteTable(
  "book_paragraphs",
  {
    bookId: text("book_id").notNull().references(() => books.id, { onDelete: "cascade" }),
    pageNumber: integer("page_number").notNull(),
    paragraphIndex: text("paragraph_index").notNull(),
    text: text("text").notNull(),
  },
  (table) => ({
    pk: primaryKey({
      columns: [table.bookId, table.pageNumber, table.paragraphIndex],
    }),
  }),
);

export type BookPage = typeof bookPages.$inferSelect;
export type NewBookPage = typeof bookPages.$inferInsert;
export type BookWord = typeof bookWords.$inferSelect;
export type NewBookWord = typeof bookWords.$inferInsert;
export type BookParagraph = typeof bookParagraphs.$inferSelect;
export type NewBookParagraph = typeof bookParagraphs.$inferInsert;

// ─── Inferred types ────────────────────────────────────────────────────────────
export type Book = typeof books.$inferSelect;
export type NewBook = typeof books.$inferInsert;
export type Highlight = typeof highlights.$inferSelect;
export type NewHighlight = typeof highlights.$inferInsert;
export type Bookmark = typeof bookmarks.$inferSelect;
export type NewBookmark = typeof bookmarks.$inferInsert;
export type ConversationRow = typeof conversations.$inferSelect;
export type NewConversation = typeof conversations.$inferInsert;
export type MessageRow = typeof messages.$inferSelect;
export type NewMessage = typeof messages.$inferInsert;

// ─── Better Auth tables ────────────────────────────────────────────────────────

export const session = sqliteTable("session", {
  id: text("id").primaryKey(),
  expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(),
  token: text("token").notNull().unique(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
});

// Better Auth's verification identifiers are polymorphic (typically an email
// address or a user id), so this table cannot safely reference user.id. The
// account-deletion service removes tokens for the deleted user's known
// identifiers explicitly.
export const verification = sqliteTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }),
  updatedAt: integer("updated_at", { mode: "timestamp" }),
});

export const passkey = sqliteTable("passkey", {
  id: text("id").primaryKey(),
  name: text("name"),
  publicKey: text("public_key").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  credentialID: text("credential_id").notNull(),
  counter: integer("counter").notNull(),
  deviceType: text("device_type").notNull(),
  backedUp: integer("backed_up", { mode: "boolean" }).notNull(),
  transports: text("transports"),
  createdAt: integer("created_at", { mode: "timestamp" }),
  aaguid: text("aaguid"),
});

// Added by @better-auth/stripe plugin. Field shape mirrors the plugin's
// auto-generated schema (packages/stripe/src/schema.ts upstream); we declare
// it manually since this repo hand-authors the Drizzle schema rather than
// running `@better-auth/cli generate`. `referenceId` is intentionally not a
// foreign key: the plugin permits references to different Better Auth scopes
// (for example, a user or organization). Account deletion removes rows whose
// referenceId is the deleted user id explicitly.
export const subscription = sqliteTable("subscription", {
  id: text("id").primaryKey(),
  plan: text("plan").notNull(),
  referenceId: text("reference_id").notNull(),
  stripeCustomerId: text("stripe_customer_id"),
  stripeSubscriptionId: text("stripe_subscription_id"),
  status: text("status").default("incomplete"),
  periodStart: integer("period_start", { mode: "timestamp" }),
  periodEnd: integer("period_end", { mode: "timestamp" }),
  trialStart: integer("trial_start", { mode: "timestamp" }),
  trialEnd: integer("trial_end", { mode: "timestamp" }),
  cancelAtPeriodEnd: integer("cancel_at_period_end", {
    mode: "boolean",
  }).default(false),
  cancelAt: integer("cancel_at", { mode: "timestamp" }),
  canceledAt: integer("canceled_at", { mode: "timestamp" }),
  endedAt: integer("ended_at", { mode: "timestamp" }),
  seats: integer("seats"),
  billingInterval: text("billing_interval"),
  stripeScheduleId: text("stripe_schedule_id"),
});

// ─── Apple IAP (Phase 14) ─────────────────────────────────────────────────────
// Table named `apple_subscriptions` (NOT `subscriptions`) — the existing
// Stripe `subscription` table already owns the unprefixed singular name.
// appleTransactionId / appleOriginalTransactionId stored as TEXT because
// Apple uses UInt64 values that overflow JS Number.MAX_SAFE_INTEGER.
// Timestamps use `timestamp_ms` mode (Apple's native ms-epoch unit), NOT
// the seconds-precision `timestamp` mode used by Better Auth tables.
export const appleSubscriptions = sqliteTable(
  "apple_subscriptions",
  {
    appleTransactionId: text("apple_transaction_id").primaryKey(),
    appleOriginalTransactionId: text("apple_original_transaction_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    productId: text("product_id").notNull(),
    status: text("status", {
      enum: ["active", "in_grace", "expired", "refunded"],
    }).notNull(),
    currentPeriodEnd: integer("current_period_end", {
      mode: "timestamp_ms",
    }).notNull(),
    environment: text("environment", {
      enum: ["Sandbox", "Production"],
    }).notNull(),
    autoRenew: integer("auto_renew", { mode: "boolean" })
      .notNull()
      .default(true),
    appAccountToken: text("app_account_token"),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .notNull()
      .$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .notNull()
      .$defaultFn(() => new Date()),
  },
  (t) => ({
    byUser: index("apple_subscriptions_user_id").on(t.userId),
    byOriginalTxn: index("apple_subscriptions_original_txn").on(
      t.appleOriginalTransactionId,
    ),
  }),
);

// Apple ASSN V2 webhook idempotency log. PK on notificationUuid lets the
// webhook handler INSERT OR IGNORE / catch UNIQUE-violation to de-dupe
// Apple's aggressive ~24h retries. user_id is nullable because some
// notifications (e.g. REFUND for a deleted user) cannot resolve a user.
export const appleNotificationsLog = sqliteTable("apple_notifications_log", {
  notificationUuid: text("notification_uuid").primaryKey(),
  notificationType: text("notification_type").notNull(),
  subtype: text("subtype"),
  userId: text("user_id").references(() => user.id, { onDelete: "cascade" }),
  appleTransactionId: text("apple_transaction_id"),
  rawPayload: text("raw_payload").notNull(),
  receivedAt: integer("received_at", { mode: "timestamp_ms" })
    .notNull()
    .$defaultFn(() => new Date()),
  processedAt: integer("processed_at", { mode: "timestamp_ms" }),
  processingError: text("processing_error"),
});

export type AppleSubscription = typeof appleSubscriptions.$inferSelect;
export type NewAppleSubscription = typeof appleSubscriptions.$inferInsert;
export type AppleNotificationLogEntry =
  typeof appleNotificationsLog.$inferSelect;
export type NewAppleNotificationLogEntry =
  typeof appleNotificationsLog.$inferInsert;

// ─── APNs device registrations (Quick-VPX VPX-02) ───────────────────────────
//
// iOS `APNsDeviceRegistrar` (RishiSync/Background/APNsDeviceRegistrar.swift)
// posts to POST /api/devices/register every time iOS hands the app a fresh
// device token. The worker persists the (userId, deviceToken) pair so the
// silent-push sync fan-out (SYNC-06) can wake every OTHER device for the
// same user. The unique index on (user_id, device_token) lets the route
// idempotently UPSERT via onConflictDoUpdate without a unique-constraint
// throw on token re-registration. `env` defaults to "production" because
// the iOS body does NOT carry an env field today — column is there for
// future-proofing only.
export const devices = sqliteTable(
  "devices",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    deviceToken: text("device_token").notNull(),
    platform: text("platform").notNull(),
    appVersion: text("app_version").notNull(),
    bundleId: text("bundle_id").notNull(),
    topic: text("topic").notNull(),
    env: text("env").notNull().default("production"),
    createdAt: integer("created_at", { mode: "timestamp_ms" })
      .notNull()
      .$defaultFn(() => new Date()),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .notNull()
      .$defaultFn(() => new Date()),
  },
  (t) => ({
    uniqUserToken: uniqueIndex("devices_user_token_uniq").on(
      t.userId,
      t.deviceToken,
    ),
  }),
);

export type Device = typeof devices.$inferSelect;
export type NewDevice = typeof devices.$inferInsert;

// ─── Usage ledger (trial credits + paid allowance periods) ──────────────────
// Durable, D1-backed records behind the UserUsageLedger Durable Object. The DO
// is the authoritative in-memory coordinator for a live decision (see the
// 2026-07-17 pricing/trial-launch design doc); these tables are what it
// persists through so reporting, audits, and DO rehydration survive a DO
// eviction. One row per user for the non-expiring trial grant; one row per
// monthly allowance period per user for paid plans; append-only reservation
// and audit rows for every accounting decision.

export const trialGrant = sqliteTable("trial_grant", {
  userId: text("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  initialCredits: integer("initial_credits").notNull().default(300),
  usedCredits: integer("used_credits").notNull().default(0),
  grantedAt: integer("granted_at", { mode: "timestamp_ms" }).notNull(),
});

// One row per monthly allowance period per user, for Reader/Voice paid plans.
// `priorPeriodId` self-references this table to chain periods across
// upgrades/renewals/crossgrades for audit (see design doc "Subscription
// transitions"). `transitionReason` records why THIS period started --
// `rollover` marks a period opened purely on wall-clock time (see
// `billing/allowance-period-rollover.ts`), as opposed to one opened by a
// freshly-verified Apple transaction.
//
// `sourceTransactionId` does double duty (`billing/entitlement-sync.ts`,
// `billing/allowance-period-rollover.ts`): (1) it is the idempotency
// marker for a transaction-triggered open -- before opening a period for
// an incoming Apple transaction, callers check whether any period already
// has that exact `transactionId` here, and skip if so; (2) every
// `rollover` period in a chain copies forward the SAME id from the period
// it supersedes, so it always traces back to the one Apple transaction
// (the original purchase or the latest renewal/upgrade/crossgrade) whose
// `apple_subscriptions` row anchors the whole paid term's validity window.
export const allowancePeriod = sqliteTable(
  "allowance_period",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    plan: text("plan", { enum: ["reader", "voice"] }).notNull(),
    periodStart: integer("period_start", { mode: "timestamp_ms" }).notNull(),
    periodEnd: integer("period_end", { mode: "timestamp_ms" }).notNull(),
    narrationSecondsTotal: integer("narration_seconds_total").notNull(),
    narrationSecondsUsed: integer("narration_seconds_used")
      .notNull()
      .default(0),
    voiceChatSecondsTotal: integer("voice_chat_seconds_total").notNull(),
    voiceChatSecondsUsed: integer("voice_chat_seconds_used")
      .notNull()
      .default(0),
    transitionReason: text("transition_reason", {
      enum: ["initial", "upgraded", "renewed", "crossgrade", "downgraded", "rollover"],
    }),
    priorPeriodId: text("prior_period_id").references(
      (): AnySQLiteColumn => allowancePeriod.id,
    ),
    sourceTransactionId: text("source_transaction_id"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  },
  (t) => ({
    byUser: index("allowance_period_user_id").on(t.userId),
    // Natural monthly bucket: rollover sets periodStart = prior periodEnd,
    // so (userId, periodStart) is the idempotency key that stops concurrent
    // /me + entitlement-sync from double-granting the same month.
    uniqUserPeriodStart: uniqueIndex("allowance_period_user_period_start_uniq").on(
      t.userId,
      t.periodStart,
    ),
  }),
);

// Pending/committed/released reservations for a single TTS generation or a
// single 30-second voice interval. `amount` is credits for `kind: "tts"`
// trial rows and seconds for paid narration/voice rows — the ledger DO knows
// which unit applies based on the user's current plan at reservation time.
export const usageReservation = sqliteTable(
  "usage_reservation",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    kind: text("kind", { enum: ["tts", "voice_interval"] }).notNull(),
    amount: integer("amount").notNull(),
    status: text("status", {
      enum: ["pending", "committed", "released"],
    }).notNull(),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
    settledAt: integer("settled_at", { mode: "timestamp_ms" }),
    metadata: text("metadata"),
  },
  (t) => ({
    byUser: index("usage_reservation_user_id").on(t.userId),
  }),
);

// Append-only audit trail for entitlement/usage decisions (grants, session
// starts/ends, hangup outcomes, reconciliation runs). `userId` is nullable
// for system-level events with no single owning user. `details` is
// JSON-serialized text (SQLite has no native JSON column type, matching the
// `raw_payload` convention already used by `apple_notifications_log`).
export const usageAuditLog = sqliteTable(
  "usage_audit_log",
  {
    id: text("id").primaryKey(),
    userId: text("user_id").references(() => user.id, {
      onDelete: "cascade",
    }),
    eventType: text("event_type").notNull(),
    details: text("details"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  },
  (t) => ({
    byUser: index("usage_audit_log_user_id").on(t.userId),
  }),
);

export type TrialGrant = typeof trialGrant.$inferSelect;
export type NewTrialGrant = typeof trialGrant.$inferInsert;
export type AllowancePeriod = typeof allowancePeriod.$inferSelect;
export type NewAllowancePeriod = typeof allowancePeriod.$inferInsert;
export type UsageReservation = typeof usageReservation.$inferSelect;
export type NewUsageReservation = typeof usageReservation.$inferInsert;
export type UsageAuditLog = typeof usageAuditLog.$inferSelect;
export type NewUsageAuditLog = typeof usageAuditLog.$inferInsert;

// ─── Ops flags (server-owned feature flags / kill switches) ────────────────
// Backs workers/worker/src/ops/feature-flags.ts. One row per flag key. See
// that module for the known flag keys, the per-flag default-when-missing
// behavior, and the 30s in-memory cache that sits in front of this table so
// most requests never touch D1 for a flag check.
export const opsFlag = sqliteTable("ops_flag", {
  key: text("key").primaryKey(),
  enabled: integer("enabled", { mode: "boolean" }).notNull().default(false),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" })
    .notNull()
    .$defaultFn(() => new Date()),
});

export type OpsFlag = typeof opsFlag.$inferSelect;
export type NewOpsFlag = typeof opsFlag.$inferInsert;
