#if canImport(UIKit)
import Foundation
import ReadiumShared

/// Sequences the read-aloud follow-highlight choreography on the navigator
/// coordinator.
///
/// Extracted from ``ReaderScreen`` (Plan 34-03, SRP): the screen's
/// `applyReadAloudHighlight()` used to flip `coordinator.isFollowingReadAloud`,
/// call `highlightReadAloudParagraph`, and kick off
/// `navigateToReadAloudParagraph` inline. That call-sequencing is a service
/// concern (it already delegates entirely to ``ReaderNavigatorCoordinator``);
/// moving it out of the view leaves the view expressing only "the active
/// paragraph changed".
///
/// `@MainActor` because the coordinator is `@MainActor`.
@MainActor
public struct ReaderReadAloudPresenter {

    private let coordinatorRef: ReaderCoordinatorRef

    public init(coordinatorRef: ReaderCoordinatorRef) {
        self.coordinatorRef = coordinatorRef
    }

    /// Pushes `paragraph` into the navigator as the active `"rishi-tts"`
    /// decoration and follows it (turning the page when it has scrolled onto a
    /// later page), or clears the decoration when `paragraph` is `nil`.
    /// No-ops until the navigator coordinator is installed.
    ///
    /// A non-nil paragraph means a read-aloud session is following the text.
    /// The coordinator separately registers the exact locations generated by
    /// auto-follow, allowing unmatched user page turns to stop/reset playback.
    /// Cleared when the session ends (paragraph -> nil).
    public func apply(paragraph: String?) {
        apply(paragraph: paragraph, locator: nil)
    }

    /// Applies the paragraph using Readium's utterance locator when one is
    /// available. This keeps highlights anchored to the correct resource as
    /// the synthesizer crosses publication content elements.
    public func apply(paragraph: String?, locator: Locator?) {
        guard let coordinator = coordinatorRef.coordinator else { return }
        coordinator.isFollowingReadAloud = paragraph != nil
        if let paragraph {
            coordinator.highlightReadAloudParagraph(paragraph, at: locator)
            // Readium supplies format-specific locators: EPUB locators carry
            // text ranges while PDF locators carry page/progression data. Use
            // that live locator whenever available so both navigators follow
            // the same publication-level pipeline.
            if let locator {
                coordinator.followReadAloudLocator(locator)
            } else {
                Task { await coordinator.navigateToReadAloudParagraph(paragraph) }
            }
        } else {
            coordinator.clearReadAloudHighlight()
        }
    }

    /// Follows the live read-aloud locator while a paragraph is playing.
    /// This keeps the viewport moving when the paragraph spans a page
    /// boundary, without changing the visible paragraph highlight.
    public func follow(locator: Locator?) {
        guard let coordinator = coordinatorRef.coordinator,
              coordinator.isFollowingReadAloud,
              let locator else { return }
        coordinator.followReadAloudLocator(locator)
    }
}
#endif
