/**
 * DAT-013 (#125): the UUID fallback used when `crypto.randomUUID` is
 * absent must produce distinct values across rapid back-to-back calls.
 *
 * The original implementation generated each byte from `Math.random()`,
 * which is fine in isolation but offers no defence against collisions
 * when the host doesn't reseed between calls (some RN runtimes have
 * historically been observed to return the same `Math.random()` sequence
 * after a fast-cold-start).
 *
 * The fix mixes a monotonically increasing per-process counter into the
 * generated bytes, guaranteeing that two synchronous calls from the
 * same JS context cannot return the same id even if `Math.random()`
 * does.
 *
 * Two sites are covered: `lib/file-import.ts` (picker + URL imports) and
 * `lib/file-handler.ts` (OS-delivered file URIs).
 *
 * NB: when the host DOES provide `crypto.randomUUID`, the function
 * delegates to it (already collision-safe). This test stubs crypto.* so
 * the fallback branch is exercised.
 */

// ── Native fakes minimal enough to import the file-import module. ───────────
type FakeFile = {
  uri: string
  exists: boolean
  write: jest.Mock
  bytes: jest.Mock
  base64: jest.Mock
  delete: jest.Mock
  copy: jest.Mock
}

const fakeFiles = new Map<string, FakeFile>()

function makeFakeFile(uri: string): FakeFile {
  const file: FakeFile = {
    uri,
    exists: true,
    write: jest.fn(),
    bytes: jest.fn(async () => new Uint8Array([1, 2, 3])),
    base64: jest.fn(async () => 'AAAA'),
    delete: jest.fn(() => {
      file.exists = false
    }),
    copy: jest.fn(),
  }
  return file
}

jest.mock('expo-file-system', () => {
  const FileCtor = jest.fn().mockImplementation((arg1: unknown, arg2?: string) => {
    let uri: string
    if (arg2 === undefined) {
      uri = typeof arg1 === 'string' ? arg1 : ((arg1 as { uri?: string })?.uri ?? '')
    } else {
      const base = typeof arg1 === 'string' ? arg1 : ((arg1 as { uri?: string })?.uri ?? '')
      uri = `${base}/${arg2}`
    }
    if (!fakeFiles.has(uri)) {
      fakeFiles.set(uri, makeFakeFile(uri))
    }
    return fakeFiles.get(uri)!
  }) as unknown as jest.Mock
  ;(FileCtor as unknown as { pickFileAsync: jest.Mock }).pickFileAsync = jest.fn()

  const DirectoryCtor = jest.fn().mockImplementation((...parts: unknown[]) => {
    const segs = parts.map((p) =>
      typeof p === 'string' ? p : ((p as { uri?: string })?.uri ?? ''),
    )
    const uri = segs.filter(Boolean).join('/')
    return {
      uri,
      exists: true,
      create: jest.fn(),
      delete: jest.fn(),
    }
  })

  return {
    File: FileCtor,
    Directory: DirectoryCtor,
    Paths: { document: '/docs' },
  }
})

jest.mock('@/lib/rag/pipeline', () => ({ embedBook: jest.fn() }))
jest.mock('@/app/_layout', () => ({ __esModule: true, IS_E2E_TEST: false }))
jest.mock('@/lib/auth', () => ({
  __esModule: true,
  getSessionToken: jest.fn(async () => null),
}))
jest.mock('@/lib/file-import-index-gate', () => ({
  __esModule: true,
  shouldSkipIndexing: jest.fn(() => true),
}))
jest.mock('@rishi/shared/schema', () => ({
  books: { id: 'id', fileHash: 'fileHash' },
}))
jest.mock('drizzle-orm', () => ({
  eq: jest.fn((col, val) => ({ col, val })),
}))
jest.mock('@/lib/db', () => ({
  db: {
    select: () => ({
      from: () => ({
        where: () => ({ get: () => undefined, all: () => [] }),
      }),
    }),
  },
}))
jest.mock('@/lib/sync/file-sync', () => ({
  __esModule: true,
  hashBookFile: jest.fn(async () => 'fresh-hash'),
}))
jest.mock('@/lib/book-import', () => ({
  createMobileBookImportService: jest.fn(() => ({
    importFromPath: jest.fn(async () => ({
      ok: true,
      bookId: 'svc',
      bookPath: '/docs/books/svc/book.epub',
      format: 'epub',
    })),
    indexBook: jest.fn(async () => undefined),
  })),
}))

// Force the fallback branch by removing crypto.randomUUID before the module
// loads. We snapshot + restore on a per-suite basis so other tests that need
// crypto.randomUUID are unaffected.
const realCrypto = globalThis.crypto

beforeEach(() => {
  // Replace crypto.randomUUID for the duration of the test to force the
  // fallback branch. We assign through `unknown` to bypass the readonly
  // randomUUID typing.
  ;(globalThis as { crypto: unknown }).crypto = {
    ...realCrypto,
    randomUUID: undefined,
  } as unknown as Crypto
})

afterEach(() => {
  globalThis.crypto = realCrypto
})

// The fallback is module-internal. We exercise it via the public API:
// `importBookFromFile` mints an id by calling generateUUID() internally
// when its caller doesn't supply one, but the simpler exposed surface is
// the e2e helper `importBookFromFile(opts.bookId)` which uses the
// CALLER-provided id (so we can't observe collision through that path).
// Instead we exercise the picker path via `importBookFile` and capture
// the id from the resolved book.
import { importBookFile } from '@/lib/file-import'
import { handleIncomingFile, __resetInFlightForTests } from '@/lib/file-handler'

// Configure expo-file-system's pickFileAsync to feed back the file URI.
import { File as ExpoFile } from 'expo-file-system'
const pickFileAsync = (
  ExpoFile as unknown as { pickFileAsync: jest.Mock }
).pickFileAsync

describe('DAT-013 — generateUUID fallback is collision-safe under rapid calls', () => {
  it('returns distinct ids across two synchronous picker imports', async () => {
    pickFileAsync.mockResolvedValueOnce({ uri: '/Downloads/a.epub' })
    pickFileAsync.mockResolvedValueOnce({ uri: '/Downloads/b.epub' })

    const [r1, r2] = await Promise.all([importBookFile(), importBookFile()])
    expect(r1.ok).toBe(true)
    expect(r2.ok).toBe(true)
    if (r1.ok && r2.ok) {
      expect(r1.book.id).not.toEqual(r2.book.id)
    }
  })

  it('returns distinct ids when Math.random returns the same value twice', async () => {
    // Pathological: pin Math.random() to a constant. Without the counter
    // mix-in the two ids would be byte-for-byte identical.
    const realRandom = Math.random
    Math.random = () => 0.5
    try {
      pickFileAsync.mockResolvedValueOnce({ uri: '/Downloads/c.epub' })
      pickFileAsync.mockResolvedValueOnce({ uri: '/Downloads/d.epub' })

      const r1 = await importBookFile()
      const r2 = await importBookFile()
      expect(r1.ok && r2.ok).toBe(true)
      if (r1.ok && r2.ok) {
        expect(r1.book.id).not.toEqual(r2.book.id)
      }
    } finally {
      Math.random = realRandom
    }
  })
})

describe('DAT-013 — file-handler generateUUID fallback is collision-safe', () => {
  beforeEach(() => {
    __resetInFlightForTests()
  })

  it('returns distinct bookIds across two synchronous incoming-file imports', async () => {
    const realRandom = Math.random
    Math.random = () => 0.5
    try {
      const [a, b] = await Promise.all([
        handleIncomingFile('file:///Inbox/a.epub'),
        handleIncomingFile('file:///Inbox/b.epub'),
      ])
      expect(a.ok && b.ok).toBe(true)
      if (a.ok && b.ok) {
        expect(a.bookId).not.toEqual(b.bookId)
      }
    } finally {
      Math.random = realRandom
    }
  })
})
