import { vi } from 'vitest'
import '@testing-library/jest-dom'

// Mock window.electron for tests
const mockElectronAPI = {
  getBooks: vi.fn().mockResolvedValue([]),
  getBook: vi.fn().mockResolvedValue(null),
  saveBook: vi.fn().mockResolvedValue({ id: 1 }),
  deleteBook: vi.fn().mockResolvedValue(undefined),
  updateBookCover: vi.fn().mockResolvedValue(undefined),
  updateBookLocation: vi.fn().mockResolvedValue(undefined),
  hasSavedEpubData: vi.fn().mockResolvedValue(false),
  savePageDataMany: vi.fn().mockResolvedValue(undefined),
  getAllPageDataByBookId: vi.fn().mockResolvedValue([]),
  searchBookText: vi.fn().mockResolvedValue([]),
  getTextFromVectorId: vi.fn().mockResolvedValue(''),
  getContextForQuery: vi.fn().mockResolvedValue([]),
  embed: vi.fn().mockResolvedValue([]),
  saveVectors: vi.fn().mockResolvedValue(undefined),
  searchVectors: vi.fn().mockResolvedValue([]),
  getBookData: vi.fn().mockResolvedValue({}),
  getPdfData: vi.fn().mockResolvedValue({}),
  getMobiData: vi.fn().mockResolvedValue({}),
  getDjvuData: vi.fn().mockResolvedValue({}),
  getMobiChapter: vi.fn().mockResolvedValue(''),
  getMobiChapterCount: vi.fn().mockResolvedValue(0),
  getMobiText: vi.fn().mockResolvedValue([]),
  getDjvuPage: vi.fn().mockResolvedValue([]),
  getDjvuPageCount: vi.fn().mockResolvedValue(0),
  getDjvuPageText: vi.fn().mockResolvedValue([]),
  checkFileSize: vi.fn().mockResolvedValue('ok'),
  unzip: vi.fn().mockResolvedValue(''),
  copyFile: vi.fn().mockResolvedValue(undefined),
  getAppDataPath: vi.fn().mockResolvedValue('/tmp/test-app-data'),
  readFile: vi.fn().mockResolvedValue(new ArrayBuffer(0)),
  writeFile: vi.fn().mockResolvedValue(undefined),
  exists: vi.fn().mockResolvedValue(false),
  mkdir: vi.fn().mockResolvedValue(undefined),
  readDir: vi.fn().mockResolvedValue([]),
  removeFile: vi.fn().mockResolvedValue(undefined),
  getDirSize: vi.fn().mockResolvedValue(0),
  getCacheFileStats: vi.fn().mockResolvedValue([]),
  processJob: vi.fn().mockResolvedValue(undefined),
  getDefaultBookFolders: vi.fn().mockResolvedValue([]),
  scanForBooks: vi.fn().mockResolvedValue(0),
  cancelScan: vi.fn().mockResolvedValue(undefined),
  clearAuth: vi.fn().mockResolvedValue(undefined),
  getUserFromStore: vi.fn().mockResolvedValue(null),
  saveUserToStore: vi.fn().mockResolvedValue(undefined),
  dumpError: vi.fn().mockResolvedValue(undefined),
  readErrorDump: vi.fn().mockResolvedValue(''),
  clearErrorDump: vi.fn().mockResolvedValue(undefined),
  getStoreValue: vi.fn().mockResolvedValue(null),
  setStoreValue: vi.fn().mockResolvedValue(undefined),
  isDev: vi.fn().mockResolvedValue(true),
  getDevBypassSecret: vi.fn().mockResolvedValue('test-secret'),
  showOpenDialog: vi.fn().mockResolvedValue({ filePaths: [] }),
  openExternal: vi.fn().mockResolvedValue(undefined),
  getOsInfo: vi.fn().mockResolvedValue({ platform: 'darwin', arch: 'arm64', version: '25.0' }),
  bookmarksList: vi.fn().mockResolvedValue([]),
  bookmarksSave: vi.fn().mockResolvedValue(undefined),
  bookmarksDelete: vi.fn().mockResolvedValue(undefined),
  highlightsList: vi.fn().mockResolvedValue([]),
  highlightsSave: vi.fn().mockResolvedValue('mock-highlight-id'),
  highlightsDelete: vi.fn().mockResolvedValue(undefined),
  highlightsDeleteById: vi.fn().mockResolvedValue(undefined),
  highlightsUpdateNote: vi.fn().mockResolvedValue(undefined),
  highlightsUpdateColor: vi.fn().mockResolvedValue(undefined),
  booksGetSyncId: vi.fn().mockResolvedValue(null),
  booksUpdateFilepath: vi.fn().mockResolvedValue(undefined),
  booksUpdateFileHash: vi.fn().mockResolvedValue(undefined),
  conversationsFindForBook: vi.fn().mockResolvedValue(null),
  conversationsCreate: vi.fn().mockResolvedValue(undefined),
  conversationsUpdateTimestamp: vi.fn().mockResolvedValue(undefined),
  messagesList: vi.fn().mockResolvedValue([]),
  messagesCreate: vi.fn().mockResolvedValue(undefined),
  messagesGetChunkPage: vi.fn().mockResolvedValue(null),
  // Sync (typed)
  syncGetDirtyBooks: vi.fn().mockResolvedValue([]),
  syncGetDirtyHighlights: vi.fn().mockResolvedValue([]),
  syncGetDirtyConversations: vi.fn().mockResolvedValue([]),
  syncGetDirtyMessages: vi.fn().mockResolvedValue([]),
  syncGetLastVersion: vi.fn().mockResolvedValue(0),
  syncMarkBooksClean: vi.fn().mockResolvedValue(undefined),
  syncMarkHighlightsClean: vi.fn().mockResolvedValue(undefined),
  syncMarkConversationsClean: vi.fn().mockResolvedValue(undefined),
  syncMarkMessagesClean: vi.fn().mockResolvedValue(undefined),
  syncApplyBookConflict: vi.fn().mockResolvedValue(undefined),
  syncApplyHighlightConflict: vi.fn().mockResolvedValue(undefined),
  syncApplyConversationConflict: vi.fn().mockResolvedValue(undefined),
  syncUpsertBook: vi.fn().mockResolvedValue(undefined),
  syncUpsertHighlight: vi.fn().mockResolvedValue(undefined),
  syncUpsertConversation: vi.fn().mockResolvedValue(undefined),
  syncInsertMessage: vi.fn().mockResolvedValue(undefined),
  syncUpdateLastVersion: vi.fn().mockResolvedValue(undefined),

  on: vi.fn().mockReturnValue(() => {}),
  once: vi.fn(),
  send: vi.fn()
}

Object.defineProperty(window, 'electron', {
  value: mockElectronAPI,
  writable: true
})
