import "@testing-library/jest-dom";

// Mock window.electron for tests
const mockElectronAPI = {
  getBooks: vi.fn().mockResolvedValue([]),
  getBook: vi.fn().mockResolvedValue(null),
  saveBook: vi.fn().mockResolvedValue({ id: 1 }),
  deleteBook: vi.fn().mockResolvedValue(undefined),
  updateBookCover: vi.fn().mockResolvedValue(undefined),
  updateBookLocation: vi.fn().mockResolvedValue(undefined),
  hasSavedEpubData: vi.fn().mockResolvedValue(false),
  savePageDataMany: vi.fn().mockResolvedValue(undefined),
  getAllPageDataByBookId: vi.fn().mockResolvedValue([]),
  searchBookText: vi.fn().mockResolvedValue([]),
  getTextFromVectorId: vi.fn().mockResolvedValue(""),
  getContextForQuery: vi.fn().mockResolvedValue([]),
  embed: vi.fn().mockResolvedValue([]),
  saveVectors: vi.fn().mockResolvedValue(undefined),
  searchVectors: vi.fn().mockResolvedValue([]),
  getBookData: vi.fn().mockResolvedValue({}),
  getPdfData: vi.fn().mockResolvedValue({}),
  getMobiData: vi.fn().mockResolvedValue({}),
  getDjvuData: vi.fn().mockResolvedValue({}),
  getMobiChapter: vi.fn().mockResolvedValue(""),
  getMobiChapterCount: vi.fn().mockResolvedValue(0),
  getMobiText: vi.fn().mockResolvedValue([]),
  getDjvuPage: vi.fn().mockResolvedValue([]),
  getDjvuPageCount: vi.fn().mockResolvedValue(0),
  getDjvuPageText: vi.fn().mockResolvedValue([]),
  checkFileSize: vi.fn().mockResolvedValue("ok"),
  unzip: vi.fn().mockResolvedValue(""),
  copyFile: vi.fn().mockResolvedValue(undefined),
  getAppDataPath: vi.fn().mockResolvedValue("/tmp/test-app-data"),
  readFile: vi.fn().mockResolvedValue(new ArrayBuffer(0)),
  writeFile: vi.fn().mockResolvedValue(undefined),
  exists: vi.fn().mockResolvedValue(false),
  mkdir: vi.fn().mockResolvedValue(undefined),
  readDir: vi.fn().mockResolvedValue([]),
  removeFile: vi.fn().mockResolvedValue(undefined),
  getDirSize: vi.fn().mockResolvedValue(0),
  getCacheFileStats: vi.fn().mockResolvedValue([]),
  processJob: vi.fn().mockResolvedValue(undefined),
  getDefaultBookFolders: vi.fn().mockResolvedValue([]),
  scanForBooks: vi.fn().mockResolvedValue(0),
  cancelScan: vi.fn().mockResolvedValue(undefined),
  getAuthToken: vi.fn().mockResolvedValue(null),
  saveAuthToken: vi.fn().mockResolvedValue(undefined),
  clearAuth: vi.fn().mockResolvedValue(undefined),
  getUserFromStore: vi.fn().mockResolvedValue(null),
  saveUserToStore: vi.fn().mockResolvedValue(undefined),
  dumpError: vi.fn().mockResolvedValue(undefined),
  readErrorDump: vi.fn().mockResolvedValue(""),
  clearErrorDump: vi.fn().mockResolvedValue(undefined),
  getStoreValue: vi.fn().mockResolvedValue(null),
  setStoreValue: vi.fn().mockResolvedValue(undefined),
  isDev: vi.fn().mockResolvedValue(true),
  getDevBypassSecret: vi.fn().mockResolvedValue("test-secret"),
  getRealtimeClientSecret: vi.fn().mockResolvedValue("test-key"),
  showOpenDialog: vi.fn().mockResolvedValue({ filePaths: [] }),
  openExternal: vi.fn().mockResolvedValue(undefined),
  getOsInfo: vi.fn().mockResolvedValue({ platform: "darwin", arch: "arm64", version: "25.0" }),
  dbQuery: vi.fn().mockResolvedValue([]),
  dbRun: vi.fn().mockResolvedValue({ changes: 0, lastInsertRowid: 0 }),
  on: vi.fn().mockReturnValue(() => {}),
  once: vi.fn(),
  send: vi.fn(),
};

Object.defineProperty(window, "electron", {
  value: mockElectronAPI,
  writable: true,
});
