import Foundation


/// Status snapshot of a realtime voice connection. Mirrors the swift-realtime-openai
/// SDK's status surface but decoupled so RishiVoice consumers never import
/// `RealtimeAPI`. Plan 10-03's `RealtimeVoiceSession` actor reads this enum;
/// the production adapter maps the SDK type into it.
public enum RealtimeConnectionStatus: String, Sendable, Equatable {
    case disconnected
    case connecting
    case connected
    case disconnecting
}

/// Role attached to a transcript fragment.
public enum TranscriptRole: String, Sendable, Equatable {
    case user
    case assistant
}

/// One transcript fragment surfaced by the SDK. `isFinal=true` indicates the
/// model marked the turn complete — Plan 10-04's `VoiceTranscriptBridge`
/// persists final fragments into `MessageStore`.
public struct RealtimeTranscriptEvent: Sendable, Equatable {
    public let role: TranscriptRole
    public let content: String
    public let isFinal: Bool
    public let timestamp: Date

    public init(
        role: TranscriptRole,
        content: String,
        isFinal: Bool,
        timestamp: Date = Date()
    ) {
        self.role = role
        self.content = content
        self.isFinal = isFinal
        self.timestamp = timestamp
    }
}

/// Error surface for the realtime client. Mirrors the SDK's `ServerError`
/// shape (code + message) without leaking the SDK type.
public struct RealtimeClientError: Error, Sendable, Equatable {
    public let code: String
    public let message: String

    public init(code: String, message: String) {
        self.code = code
        self.message = message
    }
}

/// One tool call surfaced by the realtime peer, ready to dispatch.
/// `argumentsJSON` is the SDK's `Item.FunctionCall.arguments` string verbatim —
/// the Responder (Plan 25-09) decodes it into a strongly-typed argument struct
/// (`struct BookContextArgs: Decodable { let queryText: String }`).
public struct RealtimeToolCallEvent: Sendable, Equatable {
    public let callId: String
    public let name: String
    public let argumentsJSON: String
    public let timestamp: Date

    public init(
        callId: String,
        name: String,
        argumentsJSON: String,
        timestamp: Date = Date()
    ) {
        self.callId = callId
        self.name = name
        self.argumentsJSON = argumentsJSON
        self.timestamp = timestamp
    }
}

/// Seam isolating `RealtimeVoiceSession` (Plan 10-03) from the
/// `swift-realtime-openai` SDK. Production impl: `RealtimeAPIAdapter`.
/// Test impl: `FakeRealtimeClient`.
///
/// The protocol intentionally exposes a narrow surface — open + close +
/// status snapshot + two streams. Audio capture/playback is owned by the
/// SDK internally (WebRTC peer connection); RishiVoice never sees PCM
/// frames directly. Transcript events are the only conversation-layer
/// data that crosses this boundary.
public protocol RealtimeClientAPI: Sendable {
    /// Build the local realtime transport before an ephemeral key is ready.
    /// Implementations may use this hook to overlap peer construction with
    /// server-side session setup. The transport remains disconnected and
    /// cannot send or consume audio until `connect` succeeds.
    func prewarm() async

    /// Open a WebRTC voice session with the given ephemeral key. Throws on
    /// negotiation failure (network, key rejected, SDP failure).
    func connect(
        ephemeralKey: String,
        bookContext: BookContextSnapshot?,
        language: String?,
        deferMicCapture: Bool
    ) async throws

    /// Enable or disable live WebRTC mic capture. When enabling, starts the
    /// VoIP audio unit and unmutes the local track.
    func setMicCaptureEnabled(_ enabled: Bool) async

    /// Gate assistant audio/output until activation handoff completes.
    func setAssistantOutputEnabled(_ enabled: Bool) async

    /// Cancel the response currently being generated by the realtime peer.
    /// No-op when the peer is absent or not connected.
    func cancelCurrentResponse() async

    /// Replay buffered pre-connect speech into the session (Path 0A → 0B).
    func injectBufferedInputAudio(_ pcm16le24kMono: Data) async throws -> HandoffAcceptance

    /// Plan C fallback: inject buffered speech as a text user turn.
    func injectBufferedInputText(_ text: String) async throws -> HandoffAcceptance

    /// Tear down the WebRTC session. Idempotent — calling on an already-closed
    /// client is a no-op.
    func disconnect() async

    /// Snapshot of the current connection status. Async because actor-isolated
    /// impls need a hop; SDK-backed impl reads `Conversation.status` directly.
    func currentStatus() async -> RealtimeConnectionStatus

    /// The OpenAI Realtime provider call ID captured from the `Location`
    /// header of the WebRTC call-creation response that the most recent
    /// successful `connect()` completed, per the no-card-credit-trial
    /// spec's "Voice flow" step 3. `nil` before any successful `connect()`,
    /// after `disconnect()`, or if that connect's response was missing/
    /// unparseable the header (the documented failure case that spec step
    /// 7 says must fail closed). Widens the protocol so
    /// `RealtimeVoiceSession` — which only holds `any RealtimeClientAPI` —
    /// can read the real, already-landed `RealtimeAPIAdapter.providerCallId`
    /// (see the "realtime-call-id-capture" plan's "Exports for downstream
    /// plans", which explicitly defers this widening decision to this
    /// plan). Marked `async` so a future implementation could involve a
    /// suspension point; `RealtimeAPIAdapter`'s existing synchronous
    /// lock-guarded property satisfies this requirement as-is.
    var providerCallId: String? { get async }

    /// Server-side error stream. Finishes when the client disconnects.
    func errorStream() -> AsyncStream<RealtimeClientError>

    /// Transcript-event stream. Finishes when the client disconnects.
    func transcriptStream() -> AsyncStream<RealtimeTranscriptEvent>

    /// Tool-call event stream surfaced by the realtime peer. Finishes when the
    /// client disconnects. Plan 25-09's `BookContextResponder` consumes this.
    func toolCallStream() -> AsyncStream<RealtimeToolCallEvent>

    /// Send a tool-call result back to the realtime peer. `callId` MUST match the
    /// inbound `RealtimeToolCallEvent.callId` verbatim. `payload` is a JSON string —
    /// the SDK forwards it as `Item.FunctionCallOutput.output`. Throws when not
    /// connected or when the SDK rejects the send.
    func sendToolResult(callId: String, payload: String) async throws
}

public extension RealtimeClientAPI {
    /// Test/fallback clients do not need a transport to prewarm.
    func prewarm() async {}

    func connect(ephemeralKey: String) async throws {
        try await connect(ephemeralKey: ephemeralKey, bookContext: nil, language: nil, deferMicCapture: false)
    }

    func connect(ephemeralKey: String, bookContext: BookContextSnapshot?) async throws {
        try await connect(ephemeralKey: ephemeralKey, bookContext: bookContext, language: nil, deferMicCapture: false)
    }

    func connect(
        ephemeralKey: String,
        bookContext: BookContextSnapshot?,
        language: String?
    ) async throws {
        try await connect(ephemeralKey: ephemeralKey, bookContext: bookContext, language: language, deferMicCapture: false)
    }

    func connect(
        ephemeralKey: String,
        bookContext: BookContextSnapshot?,
        language: String
    ) async throws {
        try await connect(ephemeralKey: ephemeralKey, bookContext: bookContext, language: Optional(language), deferMicCapture: false)
    }
}
