import Foundation
import Testing
@testable import rishi

@MainActor
@Suite("Root subscription native dismissal ownership — isolated storage", .serialized)
struct RootSubscriptionPresentationStateTests {
    @Test("repeated requests coalesce while the same owner's sheet remains visible")
    func visibleRequests() throws {
        let authority = SessionCredentialAuthority(persistence: CredentialStagingMemoryPersistence())
        let a = try installStagingCredentials("A", authority: authority)
        var state = RootSubscriptionPresentationState()
        state.request(a, authority: authority)
        let first = try #require(state.active)
        state.presentationDidAppear(first, authority: authority)
        state.request(a, authority: authority)
        #expect(state.active?.id == first.id)
        #expect(state.nativeDismissalReceipt?.presentationID == first.id)
        #expect(state.isPresented)
        #expect(state.pending == nil)
        #expect(try authority.snapshot() == a)
    }

    @Test("callback arriving after a closing sheet's newer request claims the original receipt")
    func callbackBeforeCapture() throws {
        let authority = SessionCredentialAuthority(persistence: CredentialStagingMemoryPersistence())
        let a = try installStagingCredentials("A", authority: authority)
        var state = RootSubscriptionPresentationState()
        state.request(a, authority: authority)
        let first = try #require(state.active)
        state.presentationDidAppear(first, authority: authority)
        #expect(authority.performIfCurrent(a.lease) { state.purchaseCompleted(presentationID: first.id) })
        state.request(a, authority: authority)
        let queued = try #require(state.pending)
        #expect(queued.id != first.id)
        #expect(state.active?.id == first.id)
        #expect(state.nativeDismissalReceipt?.presentationID == first.id)
        #expect(!state.isPresented)

        let claimedReceipt = state.claimNativeDismissal(authority: authority)
        let original = try #require(claimedReceipt)
        #expect(original.presentationID == first.id)
        #expect(original.lease == a.lease)
        #expect(original.confirmsPurchase)
        #expect(state.active?.id == queued.id)
        #expect(state.isPresented)
        state.finishDismissal(original, authority: authority)
        #expect(!state.showsConfirmation)
        #expect(state.active?.id == queued.id)
        state.purchaseCompleted(presentationID: first.id)
        #expect(state.isPresented)
        #expect(!state.pendingConfirmation)
        #expect(try authority.snapshot() == a)
    }

    @Test("account fence retains only the old native receipt across replacement and ABA", arguments: ["B", "A"])
    func accountFence(_ rawID: String) throws {
        let authority = SessionCredentialAuthority(persistence: CredentialStagingMemoryPersistence())
        let a = try installStagingCredentials("A", authority: authority)
        var state = RootSubscriptionPresentationState()
        state.request(a, authority: authority)
        let first = try #require(state.active)
        state.presentationDidAppear(first, authority: authority)
        state.purchaseCompleted(presentationID: first.id)
        state.retireForAccountFence()
        #expect(state.active == nil)
        #expect(state.pending == nil)
        #expect(!state.isPresented)
        #expect(!state.pendingConfirmation)
        #expect(!state.showsConfirmation)
        #expect(state.nativeDismissalReceipt?.presentationID == first.id)
        #expect(state.nativeDismissalReceipt?.lease == a.lease)
        let replacement = try installStagingCredentials(rawID, authority: authority)
        #expect(replacement.lease != a.lease)
        state.request(replacement, authority: authority)
        let queued = try #require(state.pending)
        #expect(state.active == nil)
        let claimedReceipt = state.claimNativeDismissal(authority: authority)
        let original = try #require(claimedReceipt)
        #expect(original.presentationID == first.id)
        #expect(original.lease == a.lease)
        #expect(!original.confirmsPurchase)
        #expect(state.active?.id == queued.id)
        #expect(state.active?.snapshot == replacement)
        #expect(state.nativeDismissalReceipt == nil)
        state.presentationDidAppear(try #require(state.active), authority: authority)
        #expect(state.nativeDismissalReceipt?.lease == replacement.lease)
        #expect(state.isPresented)
        state.finishDismissal(original, authority: authority)
        #expect(!state.showsConfirmation)
        #expect(state.active?.snapshot == replacement)
        #expect(try authority.snapshot() == replacement)
    }

    @Test("closing retains one latest current-account request, admitted after original claim")
    func latestQueuedRequest() throws {
        let authority = SessionCredentialAuthority(persistence: CredentialStagingMemoryPersistence())
        let a = try installStagingCredentials("A", authority: authority)
        var state = RootSubscriptionPresentationState()
        state.request(a, authority: authority)
        let first = try #require(state.active)
        state.presentationDidAppear(first, authority: authority)
        state.setPresented(false)
        state.request(a, authority: authority)
        let earlier = try #require(state.pending)
        state.request(a, authority: authority)
        let latest = try #require(state.pending)
        #expect(latest.id != earlier.id)
        #expect(state.nativeDismissalReceipt?.presentationID == first.id)
        let claimedReceipt = state.claimNativeDismissal(authority: authority)
        let original = try #require(claimedReceipt)
        #expect(original.presentationID == first.id)
        #expect(state.active?.id == latest.id)
        #expect(state.pending == nil)
        #expect(state.isPresented)
    }

    @Test("queued lease is revalidated at callback admission, including same raw ID reinstall", arguments: ["B", "A"])
    func staleQueue(_ rawID: String) throws {
        let authority = SessionCredentialAuthority(persistence: CredentialStagingMemoryPersistence())
        let a = try installStagingCredentials("A", authority: authority)
        var state = RootSubscriptionPresentationState()
        state.request(a, authority: authority)
        let first = try #require(state.active)
        state.presentationDidAppear(first, authority: authority)
        state.setPresented(false)
        state.request(a, authority: authority)
        #expect(state.pending != nil)
        let replacement = try installStagingCredentials(rawID, authority: authority)
        let claimedReceipt = state.claimNativeDismissal(authority: authority)
        let original = try #require(claimedReceipt)
        #expect(original.presentationID == first.id)
        #expect(original.lease == a.lease)
        #expect(state.active == nil)
        #expect(state.pending == nil)
        #expect(state.nativeDismissalReceipt == nil)
        #expect(!state.isPresented)
        state.finishDismissal(original, authority: authority)
        #expect(!state.showsConfirmation)
        #expect(try authority.snapshot() == replacement)
    }

    @Test("current purchase confirms only after its own dismissal refresh completes")
    func currentConfirmation() throws {
        let authority = SessionCredentialAuthority(persistence: CredentialStagingMemoryPersistence())
        let a = try installStagingCredentials("A", authority: authority)
        var state = RootSubscriptionPresentationState()
        state.request(a, authority: authority)
        let presented = try #require(state.active)
        state.presentationDidAppear(presented, authority: authority)
        #expect(authority.performIfCurrent(a.lease) { state.purchaseCompleted(presentationID: presented.id) })
        #expect(state.pendingConfirmation)
        #expect(!state.isPresented)
        let recordedReceipt = state.nativeDismissalReceipt
        state.presentationDidAppear(presented, authority: authority)
        #expect(state.nativeDismissalReceipt == recordedReceipt)
        #expect(state.pendingConfirmation)
        #expect(!state.isPresented)
        #expect(state.active?.id == presented.id)
        let claimedReceipt = state.claimNativeDismissal(authority: authority)
        let receipt = try #require(claimedReceipt)
        #expect(state.active == nil)
        #expect(!state.showsConfirmation)
        state.finishDismissal(receipt, authority: authority)
        #expect(state.showsConfirmation)
        state.dismissConfirmation()
        #expect(!state.showsConfirmation)
        let absentReceipt = state.claimNativeDismissal(authority: authority)
        #expect(absentReceipt == nil)
    }

    @Test("a newer same-account presentation admitted during refresh suppresses the old confirmation")
    func replacementAfterClaim() throws {
        let authority = SessionCredentialAuthority(persistence: CredentialStagingMemoryPersistence())
        let a = try installStagingCredentials("A", authority: authority)
        var state = RootSubscriptionPresentationState()
        state.request(a, authority: authority)
        let first = try #require(state.active)
        state.presentationDidAppear(first, authority: authority)
        state.purchaseCompleted(presentationID: first.id)
        let claimedReceipt = state.claimNativeDismissal(authority: authority)
        let receipt = try #require(claimedReceipt)
        state.request(a, authority: authority)
        let second = try #require(state.active)
        #expect(second.id != first.id)
        state.finishDismissal(receipt, authority: authority)
        #expect(state.isPresented)
        #expect(state.active?.id == second.id)
        #expect(!state.showsConfirmation)
    }

    @Test("account fence also invalidates an already-claimed purchase confirmation")
    func fenceDuringRefresh() throws {
        let authority = SessionCredentialAuthority(persistence: CredentialStagingMemoryPersistence())
        let a = try installStagingCredentials("A", authority: authority)
        var state = RootSubscriptionPresentationState()
        state.request(a, authority: authority)
        let presented = try #require(state.active)
        state.presentationDidAppear(presented, authority: authority)
        state.purchaseCompleted(presentationID: presented.id)
        let claimedReceipt = state.claimNativeDismissal(authority: authority)
        let receipt = try #require(claimedReceipt)
        state.retireForAccountFence()
        state.finishDismissal(receipt, authority: authority)
        #expect(!state.showsConfirmation)
        #expect(state.active == nil)
        #expect(try authority.snapshot() == a)
    }

    @Test("a never-presented request retired by an account fence does not require native dismissal")
    func neverPresentedFence() throws {
        let authority = SessionCredentialAuthority(persistence: CredentialStagingMemoryPersistence())
        let a = try installStagingCredentials("A", authority: authority)
        var state = RootSubscriptionPresentationState()
        state.request(a, authority: authority)
        #expect(state.isPresented)
        #expect(state.nativeDismissalReceipt == nil)
        state.retireForAccountFence()
        let b = try installStagingCredentials("B", authority: authority)
        state.request(b, authority: authority)
        let replacement = try #require(state.active)
        #expect(replacement.snapshot == b)
        #expect(state.isPresented)
        #expect(state.pending == nil)
        let absentReceipt = state.claimNativeDismissal(authority: authority)
        #expect(absentReceipt == nil)
        #expect(state.active?.id == replacement.id)
        state.presentationDidAppear(replacement, authority: authority)
        #expect(state.nativeDismissalReceipt?.lease == b.lease)
        #expect(try authority.snapshot() == b)
    }

    @Test("a never-presented binding dismissal releases the request for another same-account sheet")
    func neverPresentedBinding() throws {
        let authority = SessionCredentialAuthority(persistence: CredentialStagingMemoryPersistence())
        let a = try installStagingCredentials("A", authority: authority)
        var state = RootSubscriptionPresentationState()
        state.request(a, authority: authority)
        let first = try #require(state.active)
        state.setPresented(false)
        #expect(state.active == nil)
        #expect(state.nativeDismissalReceipt == nil)
        state.request(a, authority: authority)
        #expect(state.active?.id != first.id)
        #expect(state.isPresented)
        #expect(state.pending == nil)
    }

    @Test("late native appearance retains its obsolete item and queues the newer requested owner", arguments: ["B", "A", "same"])
    func lateAppearance(_ rawID: String) throws {
        let authority = SessionCredentialAuthority(persistence: CredentialStagingMemoryPersistence())
        let a = try installStagingCredentials("A", authority: authority)
        var state = RootSubscriptionPresentationState()
        state.request(a, authority: authority)
        let originalItem = try #require(state.active)
        if rawID == "same" { state.setPresented(false) }
        else { state.retireForAccountFence() }
        let replacement = rawID == "same" ? a : try installStagingCredentials(rawID, authority: authority)
        state.request(replacement, authority: authority)
        let nextItem = try #require(state.active)
        state.presentationDidAppear(originalItem, authority: authority)
        #expect(state.active == nil)
        #expect(!state.isPresented)
        #expect(state.nativeDismissalReceipt?.presentationID == originalItem.id)
        #expect(state.nativeDismissalReceipt?.lease == a.lease)
        #expect(state.pending?.id == nextItem.id)
        let claimedReceipt = state.claimNativeDismissal(authority: authority)
        let receipt = try #require(claimedReceipt)
        #expect(receipt.presentationID == originalItem.id)
        #expect(receipt.lease == a.lease)
        #expect(state.active?.id == nextItem.id)
        #expect(state.active?.snapshot == replacement)
        #expect(state.isPresented)
        state.finishDismissal(receipt, authority: authority)
        #expect(!state.showsConfirmation)
        #expect(try authority.snapshot() == replacement)
    }
}
